### ISSUE TITLE
base64.decodestring deprecated

### ISSUE THREAD

**Issue by urban-prah** [tremc/tremc#99]
The mentioned method got completely removed in Python 3.9

Quick fix:
```diff
--- tremc 2020-12-03 15:54:37.799922048 +0100
+++ tremc 2020-12-03 15:54:25.789842911 +0100
@@ -438,7 +438,7 @@
                 # TAG_TORRENT_DETAILS, but just passing seems to help.(?)
                 try:
                     torrent_details = response['arguments']['torrents'][0]
+                    torrent_details['pieces'] = base64.decodebytes(bytes(torrent_details['pieces'], ENCODING))
-                    torrent_details['pieces'] = base64.decodestring(bytes(torrent_details['pieces'], ENCODING))
                     self.torrent_details_cache = torrent_details
                     self.upgrade_peerlist()
                 except IndexError:
```

Edit: swapped +, -

**Comment by Aarnar** [comment]
Thanks for the fix but u just altered the fix , u need to remove the line having decodestring and add  the line having decodebytes.

**Comment by charlie39** [comment]
decodebytes is the current attribute. You just undid the correcttion. 🤦‍♂️🤦‍♂️🤦‍♂️

**Comment by xaidenz** [comment]
My bad. I used the wrong file order when ussing 'diff'. Edited.

**Comment by Strahinja** [comment]
Can we have a PR please?

**Comment by ilf** [comment]
This is correct in master: https://github.com/tremc/tremc/blob/master/tremc#L774

It's been correct since at least August: https://github.com/tremc/tremc/commit/243e6f1962fecbea4d8b2aff5b49f89a3c19a20e

However, it's still incorrect in 0.9.2, the last release from June: https://github.com/tremc/tremc/releases/tag/0.9.2

With Python 3.9, tremc 0.9.2 crashes:

```
File "/usr/bin/tremc", line 803, in wait_for_update
if self.update(0, update_id): break
File "/usr/bin/tremc", line 396, in update
tag = self.parse_response(response)
File "/usr/bin/tremc", line 441, in parse_response
torrent_details['pieces'] = base64.decodestring(bytes(torrent_details['pieces'], ENCODING))
AttributeError: module 'base64' has no attribute 'decodestring'
```

Would it be possible to make a new release (0.9.3), so it works with Pyton 3.9 without crashing?

Thanks, and keep up the good work!

**Comment by samyak039** [comment]
commented on Feb 5 2021 in #90 : [my comment](https://github.com/tremc/tremc/issues/90#issuecomment-774150284)
facing the same issue for a year, any way around or some quick fix ??

even the executable from this git repo is having error, this error even stops it from opening `tremc`.

this is the error, any fixes to this ?
```
Traceback (most recent call last):
  File "/home/samyak039/.local/program/tremc/./tremc", line 1316, in __init__
    self.init_screen()
  File "/home/samyak039/.local/program/tremc/./tremc", line 1349, in init_screen
    curses.cbreak()
_curses.error: cbreak() returned ERR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/samyak039/.local/program/tremc/./tremc", line 5134, in <module>
    Interface(Transmission(gconfig.url, gconfig.username, gconfig.password))
  File "/home/samyak039/.local/program/tremc/./tremc", line 1319, in __init__
    self.restore_screen()
  File "/home/samyak039/.local/program/tremc/./tremc", line 1366, in restore_screen
    curses.endwin()
_curses.error: endwin() returned ERR
```

**Comment by Strahinja** [comment]
tremc from AUR works on Artix Linux for a long time now (latest version is 0.9.2-1). Try updating your dependencies (Python, etc).

**Comment by samyak039** [comment]
hey @Strahinja, I am using Arch rn, have used Artix also. but on both system I was unable to use tremc.  
got same error on both systems

- `tremc` variant from AUR, atleast let's me view my torrent list, but I can't further open to view detailed view, at that time it crashes cause of the above mentioned error.

- `tremc-git` variant from AUR, it won't even open tremc, and when I tried to redirect the error message this is what I get, right now:
```
Traceback (most recent call last):
  File "/tmp/tremc/./tremc", line 5141, in <module>
    Interface(Transmission(gconfig.url, gconfig.username, gconfig.password))
  File "/tmp/tremc/./tremc", line 1316, in __init__
    self.init_screen()
  File "/tmp/tremc/./tremc", line 1353, in init_screen
    self.colors = ColorManager(dict(config.items('Colors')))
  File "/tmp/tremc/./tremc", line 455, in __init__
    self.config[name] = self._parse_color_pair(config[name])
  File "/tmp/tremc/./tremc", line 463, in _parse_color_pair
    fg_name = [x for x in pair.split(',') if x[:3] == 'fg:'][0].split(':')[1].upper() if 'fg:' in pair else 'DEFAULT'
IndexError: list index out of range
```
- I even tried cloning the git repo, but got the same result as `tremc-git`, cause they are same XD

when the python got updated to version 3.10 I got excited that may be tremc will work now, but got no luck.

then today I stumbled upon the tremc's readme, and python v3.2 was mentioned in it's dependency, so I tried `python32` package from AUR, still tremc won't even open :(

**Comment by Strahinja** [comment]
Ok, there has been something weird going on with tremc definitely. The [commits page][1] shows some commits being pushed on February 27th 2021, but those commits are from October and November 2020 according to the git log in the cloned repository (that I cloned prior to February 27th). There might be some force-pushing by the devs? At the same time, version isn't bumped, so the AUR package `tremc` that I installed prior to February 27th wasn't updated and continued to work as normal. When I uninstalled and reinstalled (with rebuild) `tremc` from AUR, it did error out.

However, freshly installed `tremc-git` works. I can switch to different tabs ("Overview"/"Files"/"Peers" etc) and it doesn't crash.

Maybe the problem on your side is in
```
/tmp/tremc/./tremc
```
Why is tremc located in /tmp? You should install it, in /usr/bin.

[1]: https://github.com/tremc/tremc/commits/master

**Comment by gangelop** [comment]
There have been some very big changes since `0.9.2` which are merged into the master branch and still more pull requests that I haven't reviewed and have not merged. Since those changes were made quite a while ago and people have been using the master branch through `tremc-git` from the AUR, I just now marked a `0.9.3` tag to help avoid some of this recurring confusion.

In short: I just marked the current HEAD of master as `0.9.3` but there have been no changes merged since February of last year.

**Comment by samyak039** [comment]
> Why is tremc located in /tmp? You should install it, in /usr/bin.

because I was trying the git repo, so I cloned it in `/tmp`

thanks @Strahinja, ig I'm dumb, I haven't updated my config file in a file, as a result was unable to run the newer `tremc`.
